name: seg_medico2
description: "Applicazione per la gestione della segreteria medica."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.1
  uuid: ^4.4.0
  drift: ^2.28.0 # Usa la versione più recente
  sqlite3_flutter_libs: ^0.5.38 # Per il supporto SQLite su Flutter
  path_provider: ^2.1.5 # Per trovare la directory del database
  path: ^1.9.0 # Per la gestione dei percorsi
  flutter_secure_storage: ^9.0.0 # Per salvare token in modo sicuro
  rxdart: ^0.27.7

  # UI & Stile
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  
  # Gestione Stato
  provider: ^6.1.2
  
  # Utility
  intl: ^0.19.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.2.3 # Per salvare i profili
  http: ^1.2.1 # Per le chiamate API
  
  # Componenti UI Specifici
  flutter_speed_dial: ^7.0.0
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.6.0
  drift_dev: ^2.28.1-dev.0 # Usa la versione più recente


flutter:
  uses-material-design: true
