// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: app_studiomedico

#ifndef UI_SEGRETERIAMEDICO_H
#define UI_SEGRETERIAMEDICO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SEGRETERIAMEDICO
extern void ui_SEGRETERIAMEDICO_screen_init(void);
extern void ui_SEGRETERIAMEDICO_screen_destroy(void);
extern lv_obj_t * ui_SEGRETERIAMEDICO;
extern lv_obj_t * ui_TAB;
extern lv_obj_t * ui_FARMACI;
extern lv_obj_t * ui_APPUNTAMENTI;
extern lv_obj_t * ui_ContainerFARMACI;
extern lv_obj_t * ui_Checkbox2;
extern lv_obj_t * ui_Checkbox3;
extern lv_obj_t * ui_Checkbox4;
extern lv_obj_t * ui_Checkbox5;
extern lv_obj_t * ui_Checkbox6;
extern lv_obj_t * ui_ciao;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SEGRETERIAMEDICO;
extern lv_obj_t * uic_FARMACI;
extern lv_obj_t * uic_ContainerFARMACI;
extern lv_obj_t * uic_ciao;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

