// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: app_studiomedico

#include "../ui.h"

lv_obj_t * uic_ciao;
lv_obj_t * uic_ContainerFARMACI;
lv_obj_t * uic_FARMACI;
lv_obj_t * uic_SEGRETERIAMEDICO;
lv_obj_t * ui_SEGRETERIAMEDICO = NULL;
lv_obj_t * ui_TAB = NULL;
lv_obj_t * ui_FARMACI = NULL;
lv_obj_t * ui_APPUNTAMENTI = NULL;
lv_obj_t * ui_ContainerFARMACI = NULL;
lv_obj_t * ui_Checkbox2 = NULL;
lv_obj_t * ui_Checkbox3 = NULL;
lv_obj_t * ui_Checkbox4 = NULL;
lv_obj_t * ui_Checkbox5 = NULL;
lv_obj_t * ui_Checkbox6 = NULL;
lv_obj_t * ui_ciao = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions

// build funtions

void ui_SEGRETERIAMEDICO_screen_init(void)
{
    ui_SEGRETERIAMEDICO = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SEGRETERIAMEDICO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SEGRETERIAMEDICO, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SEGRETERIAMEDICO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TAB = lv_tabview_create(ui_SEGRETERIAMEDICO, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TAB, lv_pct(100));
    lv_obj_set_height(ui_TAB, lv_pct(87));
    lv_obj_set_x(ui_TAB, -1);
    lv_obj_set_y(ui_TAB, 54);
    lv_obj_set_align(ui_TAB, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TAB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FARMACI = lv_tabview_add_tab(ui_TAB, "FARMACI");
    lv_obj_set_style_text_color(ui_FARMACI, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FARMACI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_APPUNTAMENTI = lv_tabview_add_tab(ui_TAB, "APPUNTAMENTI");

    ui_ContainerFARMACI = lv_obj_create(ui_SEGRETERIAMEDICO);
    lv_obj_remove_style_all(ui_ContainerFARMACI);
    lv_obj_set_height(ui_ContainerFARMACI, 423);
    lv_obj_set_width(ui_ContainerFARMACI, lv_pct(100));
    lv_obj_set_x(ui_ContainerFARMACI, 0);
    lv_obj_set_y(ui_ContainerFARMACI, -16);
    lv_obj_set_align(ui_ContainerFARMACI, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerFARMACI, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerFARMACI, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerFARMACI, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_ContainerFARMACI, LV_DIR_VER);
    lv_obj_set_style_pad_row(ui_ContainerFARMACI, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerFARMACI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox2 = lv_checkbox_create(ui_ContainerFARMACI);
    lv_checkbox_set_text(ui_Checkbox2, "test di lunghezza ");
    lv_obj_set_width(ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox2, -170);
    lv_obj_set_y(ui_Checkbox2, -223);
    lv_obj_set_align(ui_Checkbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox3 = lv_checkbox_create(ui_ContainerFARMACI);
    lv_obj_set_width(ui_Checkbox3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox3, -168);
    lv_obj_set_y(ui_Checkbox3, -185);
    lv_obj_set_align(ui_Checkbox3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox4 = lv_checkbox_create(ui_ContainerFARMACI);
    lv_obj_set_width(ui_Checkbox4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox4, 13);
    lv_obj_set_y(ui_Checkbox4, 169);
    lv_obj_set_align(ui_Checkbox4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox4, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox5 = lv_checkbox_create(ui_ContainerFARMACI);
    lv_obj_set_width(ui_Checkbox5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Checkbox5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox5, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox6 = lv_checkbox_create(ui_ContainerFARMACI);
    lv_obj_set_width(ui_Checkbox6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Checkbox6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox6, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ciao = lv_btn_create(ui_SEGRETERIAMEDICO);
    lv_obj_set_width(ui_ciao, 368);
    lv_obj_set_height(ui_ciao, 50);
    lv_obj_set_x(ui_ciao, 1);
    lv_obj_set_y(ui_ciao, 268);
    lv_obj_set_align(ui_ciao, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ciao, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ciao, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_ciao, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ciao, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ciao, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ciao, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_ciao, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_ciao, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_ciao, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_ciao, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_ciao, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Label1 = lv_label_create(ui_SEGRETERIAMEDICO);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 268);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "CONFERMA LISTA");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_SEGRETERIAMEDICO);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 463);
    lv_obj_set_height(ui_Container1, 89);
    lv_obj_set_x(ui_Container1, -3);
    lv_obj_set_y(ui_Container1, -347);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_SEGRETERIAMEDICO);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 50);
    lv_obj_set_y(ui_Label2, -351);
    lv_obj_set_align(ui_Label2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label2, "OSPITE");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_SEGRETERIAMEDICO);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_height(ui_Container2, lv_pct(10));
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 360);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x4D4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label3, lv_pct(97));
    lv_obj_set_height(ui_Label3, lv_pct(79));
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Premi su \"ACCEDI\" per inviare la lista o per prendere un appunamento.");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xAF8B00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_SEGRETERIAMEDICO);
    lv_obj_set_width(ui_Button2, 140);
    lv_obj_set_height(ui_Button2, 30);
    lv_obj_set_x(ui_Button2, 61);
    lv_obj_set_y(ui_Button2, -352);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_SEGRETERIAMEDICO);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 64);
    lv_obj_set_y(ui_Label4, -352);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "ACCEDI");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_SEGRETERIAMEDICO = ui_SEGRETERIAMEDICO;
    uic_FARMACI = ui_FARMACI;
    uic_ContainerFARMACI = ui_ContainerFARMACI;
    uic_ciao = ui_ciao;

}

void ui_SEGRETERIAMEDICO_screen_destroy(void)
{
    if(ui_SEGRETERIAMEDICO) lv_obj_del(ui_SEGRETERIAMEDICO);

    // NULL screen variables
    uic_SEGRETERIAMEDICO = NULL;
    ui_SEGRETERIAMEDICO = NULL;
    ui_TAB = NULL;
    uic_FARMACI = NULL;
    ui_FARMACI = NULL;
    ui_APPUNTAMENTI = NULL;
    uic_ContainerFARMACI = NULL;
    ui_ContainerFARMACI = NULL;
    ui_Checkbox2 = NULL;
    ui_Checkbox3 = NULL;
    ui_Checkbox4 = NULL;
    ui_Checkbox5 = NULL;
    ui_Checkbox6 = NULL;
    uic_ciao = NULL;
    ui_ciao = NULL;
    ui_Label1 = NULL;
    ui_Container1 = NULL;
    ui_Label2 = NULL;
    ui_Container2 = NULL;
    ui_Label3 = NULL;
    ui_Button2 = NULL;
    ui_Label4 = NULL;

}
